/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mafer
 */

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
public class MeetGUI extends javax.swing.JFrame {

    /**
     * Creates new form MeetGUI
     */
    private Departamento depa;
    private GraficaH gh;
    private GraficaR gr;
    private GraficaL gl;
    private String nombreH;
    private int vectorCali[];
    public MeetGUI() {
        try {
            Mongo db = new Mongo("localhost", 27017);
        } catch (UnknownHostException ex) {
            Logger.getLogger(MeetGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        //depa = new Departamento();
        //gh = new GraficaH();
        //gr = new GraficaR();
        //gl = new GraficaL();
        nombreH="";
        vectorCali = new int[5];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clases = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cbNombre = new javax.swing.JComboBox<>();
        rbHotel = new javax.swing.JRadioButton();
        rbRes = new javax.swing.JRadioButton();
        rbLugar = new javax.swing.JRadioButton();
        rbEvento = new javax.swing.JRadioButton();
        rbActividad = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        graficas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pb5 = new javax.swing.JProgressBar();
        pb4 = new javax.swing.JProgressBar();
        pb3 = new javax.swing.JProgressBar();
        pb2 = new javax.swing.JProgressBar();
        pb1 = new javax.swing.JProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione un departamento:");

        jComboBox1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta Verapaz", "Baja Verapaz", "Escuintla", "Guatemala", "Santa Rosa" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jButton1.setText("Ver información completa del departamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNombreActionPerformed(evt);
            }
        });

        Clases.add(rbHotel);
        rbHotel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rbHotel.setText("Hotel");
        rbHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHotelActionPerformed(evt);
            }
        });

        Clases.add(rbRes);
        rbRes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rbRes.setText("Restaurante");
        rbRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbResActionPerformed(evt);
            }
        });

        Clases.add(rbLugar);
        rbLugar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rbLugar.setText("Lugar Turistico");
        rbLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLugarActionPerformed(evt);
            }
        });

        Clases.add(rbEvento);
        rbEvento.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rbEvento.setText("Evento");
        rbEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEventoActionPerformed(evt);
            }
        });

        Clases.add(rbActividad);
        rbActividad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rbActividad.setText("Actividad");
        rbActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActividadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione lo que desea buscar:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione el nombre:");

        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 0, 13)); // NOI18N
        jButton2.setText("Ver información");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbHotel)
                            .addComponent(rbRes))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbEvento)
                                    .addComponent(rbLugar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(rbActividad)))))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(156, 156, 156))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHotel)
                            .addComponent(rbLugar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbRes)
                            .addComponent(rbEvento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbActividad)
                        .addGap(53, 53, 53)))
                .addComponent(cbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton2)
                .addContainerGap())
        );

        graficas.setBorder(javax.swing.BorderFactory.createTitledBorder("Reseña de calificaciones"));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setText("5");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setText("4");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setText("3");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel7.setText("2");

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel8.setText("1");

        pb5.setMaximum(75);

        pb4.setMaximum(75);

        pb3.setMaximum(75);

        pb2.setMaximum(75);

        pb1.setMaximum(75);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Calificacion actual:");

        jTextField1.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Calificar ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI Historic", 0, 13)); // NOI18N
        jButton7.setText("Calificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout graficasLayout = new javax.swing.GroupLayout(graficas);
        graficas.setLayout(graficasLayout);
        graficasLayout.setHorizontalGroup(
            graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(pb4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(pb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(graficasLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(pb5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(27, 27, 27)))
                .addContainerGap())
        );
        graficasLayout.setVerticalGroup(
            graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graficasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(pb5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(graficasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pb1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(graficasLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap())
        );

        jButton4.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jButton4.setText("Mejores Hoteles");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jButton5.setText("Mejores Restaurentes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jButton6.setText("Mejores lugares turisticos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel9.setText("Selecciona el de tu preferencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graficas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(83, 83, 83))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)))))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jButton4)
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(graficas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(61, 61, 61)
                        .addComponent(jButton6)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombredepa = String.valueOf(jComboBox1.getSelectedItem());
        jTextArea1.setText(depa.busquerAct(nombredepa) + "\n" +"\nHoteles:" + "\n" +depa.busquerHoteles(nombredepa) + depa.busquerEvento(nombredepa) + depa.busquerLugar(nombredepa) + depa.busquerRestaurante(nombredepa));
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHotelActionPerformed
        // TODO add your handling code here:
        ArrayList<Hotel> nombres = depa.busquerNombreH(String.valueOf(jComboBox1.getSelectedItem()));
        for(int i=0; i<nombres.size(); i++){
            cbNombre.addItem(String.valueOf(nombres.get(i).getNombre()));
                   
        }
        
    }//GEN-LAST:event_rbHotelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        if(rbHotel.isSelected()){
            String nombredepa = String.valueOf(cbNombre.getSelectedItem());
            jTextArea1.setText(depa.infoHotel(nombredepa));
            nombreH = String.valueOf(cbNombre.getSelectedItem());
            vectorCali = depa.cantidadCH(nombreH);
            pb1.setValue(vectorCali[0]);
            pb2.setValue(vectorCali[1]);
            pb3.setValue(vectorCali[2]);
            pb4.setValue(vectorCali[3]);
            pb5.setValue(vectorCali[4]);
                  
                       
            cbNombre.removeAllItems();
            
            
        }else if (rbEvento.isSelected()){
            String nombredepa = String.valueOf(cbNombre.getSelectedItem());
            jTextArea1.setText(depa.infoEvento(nombredepa));
            nombreH = String.valueOf(cbNombre.getSelectedItem());
            
            
            
        }else if (rbRes.isSelected()){
            String nombredepa = String.valueOf(cbNombre.getSelectedItem());
            jTextArea1.setText(depa.infoRes(nombredepa));
            nombreH=String.valueOf(cbNombre.getSelectedItem());
            vectorCali = depa.cantidadCR(nombreH);
            pb1.setValue(vectorCali[0]);
            pb2.setValue(vectorCali[1]);
            pb3.setValue(vectorCali[2]);
            pb4.setValue(vectorCali[3]);
            pb5.setValue(vectorCali[4]);
            
            cbNombre.removeAllItems();
            
        } else if (rbLugar.isSelected()){
            String nombredepa = String.valueOf(cbNombre.getSelectedItem());
            jTextArea1.setText(depa.infoLugar(nombredepa));
           
            nombreH=String.valueOf(cbNombre.getSelectedItem());
            vectorCali = depa.cantidadCL(nombreH);
            pb1.setValue(vectorCali[0]);
            pb2.setValue(vectorCali[1]);
            pb3.setValue(vectorCali[2]);
            pb4.setValue(vectorCali[3]);
            pb5.setValue(vectorCali[4]);
            cbNombre.removeAllItems();
        } else if (rbActividad.isSelected()){
            String nombredepa = String.valueOf(cbNombre.getSelectedItem());
            jTextArea1.setText(depa.infoActividad(nombredepa));
            
            nombreH=String.valueOf(cbNombre.getSelectedItem());
            cbNombre.removeAllItems();
        }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, "Por favor seleccione una opcion de lo que desea buscar en el panel de arriba");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLugarActionPerformed
        // TODO add your handling code here:
        ArrayList<LugarT> nombres = depa.buscarNombreL(String.valueOf(jComboBox1.getSelectedItem()));
        for(int i=0; i<nombres.size(); i++){
            cbNombre.addItem(nombres.get(i).getNombre());
        }
    }//GEN-LAST:event_rbLugarActionPerformed

    private void rbResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbResActionPerformed
        // TODO add your handling code here:
        ArrayList<Restaurante> nombres = depa.buscarNombreR(String.valueOf(jComboBox1.getSelectedItem()));
        for(int i=0; i<nombres.size(); i++){
            cbNombre.addItem(nombres.get(i).getNombre());
        }
    }//GEN-LAST:event_rbResActionPerformed

    private void rbEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEventoActionPerformed
        // TODO add your handling code here:
        ArrayList<Evento> nombres = depa.buscarNombreE(String.valueOf(jComboBox1.getSelectedItem()));
        for(int i=0; i<nombres.size(); i++){
            cbNombre.addItem(nombres.get(i).getNombre());
        }
    }//GEN-LAST:event_rbEventoActionPerformed

    private void rbActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActividadActionPerformed
        // TODO add your handling code here:
        ArrayList<Actividad> nombres = depa.buscarNombreA(String.valueOf(jComboBox1.getSelectedItem()));
        for(int i=0; i<nombres.size(); i++){
            cbNombre.addItem(nombres.get(i).getNombre());
        }
    }//GEN-LAST:event_rbActividadActionPerformed

    private void cbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNombreActionPerformed
        // TODO add your handling code here:
                        
    }//GEN-LAST:event_cbNombreActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:


        
        
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        String val=String.valueOf(jComboBox2.getSelectedItem());
        String criterio= nombreH;
        
        
        
        if(rbHotel.isSelected()){
            
        int conteoCal=depa.calificacionHBarra(val, criterio);
        double conteoCalT=depa.calificacionHTotal(criterio);
        int[] vectorC=depa.cantidadCH(criterio);
        double calculo=vectorC[0];
        
        pb1.setValue((int) calculo);
        double calculo2= vectorC[1];
        pb2.setValue((int) calculo2);
        double calculo3= vectorC[2];
        pb3.setValue((int) calculo3);
        double calculo4= vectorC[3];
        pb4.setValue((int) calculo4);
        double calculo5= vectorC[4];
        pb5.setValue((int) calculo5);
        DecimalFormat df = new DecimalFormat("#.##");
        double x=depa.calificacionH(criterio);
        jTextField1.setText(String.valueOf(df.format(x)));
        
        
        
        
        } else if(rbRes.isSelected()){
            
            int conteoCal=depa.calificacionRBarra(val, criterio);
            double conteoCalT=depa.calificacionRTotal(criterio);
            int[] vectorC=depa.cantidadCR(criterio);
            double calculo=(vectorC[0]/conteoCalT)*100;
        
            pb1.setValue((int) calculo);
            double calculo2= (vectorC[1]/conteoCalT)*100;
            pb2.setValue((int) calculo2);
            double calculo3= (vectorC[2]/conteoCalT)*100;
            pb3.setValue((int) calculo3);
            double calculo4= (vectorC[3]/conteoCalT)*100;
            pb4.setValue((int) calculo4);
            double calculo5= (vectorC[4]/conteoCalT)*100;
            pb5.setValue((int) calculo5);
            DecimalFormat df = new DecimalFormat("#.##");
            double x=depa.calificacionR(criterio);
            
        } else if(rbLugar.isSelected()){
            int conteoCal=depa.calificacionLBarra(val, criterio);
            double conteoCalT=depa.calificacionLTotal(criterio);
            int[] vectorC=depa.cantidadCL(criterio);
            double calculo=(vectorC[0]/conteoCalT)*100;
        
            pb1.setValue((int) calculo);
            double calculo2= (vectorC[1]/conteoCalT)*100;
            pb2.setValue((int) calculo2);
            double calculo3= (vectorC[2]/conteoCalT)*100;
            pb3.setValue((int) calculo3);
            double calculo4= (vectorC[3]/conteoCalT)*100;
            pb4.setValue((int) calculo4);
            double calculo5= (vectorC[4]/conteoCalT)*100;
            pb5.setValue((int) calculo5);
            DecimalFormat df = new DecimalFormat("#.##");
            double x=depa.calificacionL(criterio);
            
        }


         
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Hotel[] hotel = depa.convertiH();
       	gh.crearGrafica(hotel);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Restaurante[] res = depa.convertirR();
        gr.crearGrafica(res);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LugarT[] lugar = depa.convertirL();
        gl.crearGrafica(lugar);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeetGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Clases;
    private javax.swing.JComboBox<String> cbNombre;
    private javax.swing.JPanel graficas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JProgressBar pb1;
    private javax.swing.JProgressBar pb2;
    private javax.swing.JProgressBar pb3;
    private javax.swing.JProgressBar pb4;
    private javax.swing.JProgressBar pb5;
    private javax.swing.JRadioButton rbActividad;
    private javax.swing.JRadioButton rbEvento;
    private javax.swing.JRadioButton rbHotel;
    private javax.swing.JRadioButton rbLugar;
    private javax.swing.JRadioButton rbRes;
    // End of variables declaration//GEN-END:variables
}
